name: arc_env
channels:
  - defaults
  - rmg
  - conda-forge
  - psi4
dependencies:
  - cairo
  - cairocffi
  - rmg::cantera >=2.3.0
  - conda-forge::cclib >=1.6.3
  - rmg::chemprop
  - coolprop
  - coverage
  - cython >=0.25.2
  - ffmpeg
  - rmg::gprof2dot
  - anaconda::graphviz
  - h5py
  - jinja2
  - jupyter
  - rmg::lpsolve55
  - markupsafe
  - matplotlib >=1.5
  - rmg::mopac
  - mpmath
  - rmg::muq2
  - networkx
  - nose
  - rmg::numdifftools
  - numpy >=1.10.0
  - conda-forge::openbabel >= 3
  - pandas
  - psutil
  - rmg::pydas >=1.0.2
  - pydot
  - rmg::pydqed >=1.0.1
  - pymongo
  - pyparsing
  - rmg::pyrdl
  - python >=3.7
  - pyyaml
  - rmg::quantities
  - rmg::rdkit >=2020.03.3.0
  - scikit-learn
  - scipy
  - rmg::symmetry
  - xlrd
  - xlwt
  - conda-forge::ase >=3.15.0
  - anaconda::ipython
  - mako
  - more-itertools
  - anaconda::paramiko >=2.6.0
  - conda-forge::py3dmol >= 0.8.0
  - pytables
  - psi4::psi4
  - anaconda::sphinx
  - anaconda::sphinx_rtd_theme
  - conda-forge::qcelemental
